modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="switchots_craft"
version="1.0.0"
displayName="Switchot's Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="cswit, MCreator"

[[dependencies.switchots_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.switchots_craft]]
    modId="JEI"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

