
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.switchotscraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.switchotscraft.block.P9Block;
import net.mcreator.switchotscraft.block.P99Block;
import net.mcreator.switchotscraft.block.P98Block;
import net.mcreator.switchotscraft.block.P97Block;
import net.mcreator.switchotscraft.block.P96Block;
import net.mcreator.switchotscraft.block.P95Block;
import net.mcreator.switchotscraft.block.P94Block;
import net.mcreator.switchotscraft.block.P93Block;
import net.mcreator.switchotscraft.block.P92Block;
import net.mcreator.switchotscraft.block.P91Block;
import net.mcreator.switchotscraft.block.P90Block;
import net.mcreator.switchotscraft.block.P8Block;
import net.mcreator.switchotscraft.block.P89Block;
import net.mcreator.switchotscraft.block.P88Block;
import net.mcreator.switchotscraft.block.P87Block;
import net.mcreator.switchotscraft.block.P86Block;
import net.mcreator.switchotscraft.block.P85Block;
import net.mcreator.switchotscraft.block.P84Block;
import net.mcreator.switchotscraft.block.P83Block;
import net.mcreator.switchotscraft.block.P82Block;
import net.mcreator.switchotscraft.block.P81Block;
import net.mcreator.switchotscraft.block.P80Block;
import net.mcreator.switchotscraft.block.P7Block;
import net.mcreator.switchotscraft.block.P79Block;
import net.mcreator.switchotscraft.block.P78Block;
import net.mcreator.switchotscraft.block.P77Block;
import net.mcreator.switchotscraft.block.P76Block;
import net.mcreator.switchotscraft.block.P75Block;
import net.mcreator.switchotscraft.block.P74Block;
import net.mcreator.switchotscraft.block.P73Block;
import net.mcreator.switchotscraft.block.P72Block;
import net.mcreator.switchotscraft.block.P71Block;
import net.mcreator.switchotscraft.block.P70Block;
import net.mcreator.switchotscraft.block.P6Block;
import net.mcreator.switchotscraft.block.P69Block;
import net.mcreator.switchotscraft.block.P68Block;
import net.mcreator.switchotscraft.block.P67Block;
import net.mcreator.switchotscraft.block.P66Block;
import net.mcreator.switchotscraft.block.P65Block;
import net.mcreator.switchotscraft.block.P64Block;
import net.mcreator.switchotscraft.block.P63Block;
import net.mcreator.switchotscraft.block.P62Block;
import net.mcreator.switchotscraft.block.P61Block;
import net.mcreator.switchotscraft.block.P60Block;
import net.mcreator.switchotscraft.block.P5Block;
import net.mcreator.switchotscraft.block.P59Block;
import net.mcreator.switchotscraft.block.P58Block;
import net.mcreator.switchotscraft.block.P57Block;
import net.mcreator.switchotscraft.block.P56Block;
import net.mcreator.switchotscraft.block.P55Block;
import net.mcreator.switchotscraft.block.P54Block;
import net.mcreator.switchotscraft.block.P53Block;
import net.mcreator.switchotscraft.block.P52Block;
import net.mcreator.switchotscraft.block.P51Block;
import net.mcreator.switchotscraft.block.P50Block;
import net.mcreator.switchotscraft.block.P4Block;
import net.mcreator.switchotscraft.block.P49Block;
import net.mcreator.switchotscraft.block.P48Block;
import net.mcreator.switchotscraft.block.P47Block;
import net.mcreator.switchotscraft.block.P46Block;
import net.mcreator.switchotscraft.block.P45Block;
import net.mcreator.switchotscraft.block.P44Block;
import net.mcreator.switchotscraft.block.P43Block;
import net.mcreator.switchotscraft.block.P42Block;
import net.mcreator.switchotscraft.block.P41Block;
import net.mcreator.switchotscraft.block.P40Block;
import net.mcreator.switchotscraft.block.P3Block;
import net.mcreator.switchotscraft.block.P39Block;
import net.mcreator.switchotscraft.block.P38Block;
import net.mcreator.switchotscraft.block.P37Block;
import net.mcreator.switchotscraft.block.P36Block;
import net.mcreator.switchotscraft.block.P35Block;
import net.mcreator.switchotscraft.block.P34Block;
import net.mcreator.switchotscraft.block.P33Block;
import net.mcreator.switchotscraft.block.P32Block;
import net.mcreator.switchotscraft.block.P31Block;
import net.mcreator.switchotscraft.block.P30Block;
import net.mcreator.switchotscraft.block.P2Block;
import net.mcreator.switchotscraft.block.P29Block;
import net.mcreator.switchotscraft.block.P28Block;
import net.mcreator.switchotscraft.block.P27Block;
import net.mcreator.switchotscraft.block.P26Block;
import net.mcreator.switchotscraft.block.P25Block;
import net.mcreator.switchotscraft.block.P24Block;
import net.mcreator.switchotscraft.block.P23Block;
import net.mcreator.switchotscraft.block.P22Block;
import net.mcreator.switchotscraft.block.P21Block;
import net.mcreator.switchotscraft.block.P20Block;
import net.mcreator.switchotscraft.block.P1Block;
import net.mcreator.switchotscraft.block.P19Block;
import net.mcreator.switchotscraft.block.P18Block;
import net.mcreator.switchotscraft.block.P17Block;
import net.mcreator.switchotscraft.block.P16Block;
import net.mcreator.switchotscraft.block.P15Block;
import net.mcreator.switchotscraft.block.P14Block;
import net.mcreator.switchotscraft.block.P13Block;
import net.mcreator.switchotscraft.block.P12Block;
import net.mcreator.switchotscraft.block.P11Block;
import net.mcreator.switchotscraft.block.P10Block;
import net.mcreator.switchotscraft.block.P100Block;
import net.mcreator.switchotscraft.block.L9Block;
import net.mcreator.switchotscraft.block.L99Block;
import net.mcreator.switchotscraft.block.L98Block;
import net.mcreator.switchotscraft.block.L97Block;
import net.mcreator.switchotscraft.block.L96Block;
import net.mcreator.switchotscraft.block.L95Block;
import net.mcreator.switchotscraft.block.L94Block;
import net.mcreator.switchotscraft.block.L93Block;
import net.mcreator.switchotscraft.block.L92Block;
import net.mcreator.switchotscraft.block.L91Block;
import net.mcreator.switchotscraft.block.L90Block;
import net.mcreator.switchotscraft.block.L8Block;
import net.mcreator.switchotscraft.block.L89Block;
import net.mcreator.switchotscraft.block.L88Block;
import net.mcreator.switchotscraft.block.L87Block;
import net.mcreator.switchotscraft.block.L86Block;
import net.mcreator.switchotscraft.block.L85Block;
import net.mcreator.switchotscraft.block.L84Block;
import net.mcreator.switchotscraft.block.L83Block;
import net.mcreator.switchotscraft.block.L82Block;
import net.mcreator.switchotscraft.block.L81Block;
import net.mcreator.switchotscraft.block.L80Block;
import net.mcreator.switchotscraft.block.L7Block;
import net.mcreator.switchotscraft.block.L79Block;
import net.mcreator.switchotscraft.block.L78Block;
import net.mcreator.switchotscraft.block.L77Block;
import net.mcreator.switchotscraft.block.L76Block;
import net.mcreator.switchotscraft.block.L75Block;
import net.mcreator.switchotscraft.block.L74Block;
import net.mcreator.switchotscraft.block.L73Block;
import net.mcreator.switchotscraft.block.L72Block;
import net.mcreator.switchotscraft.block.L71Block;
import net.mcreator.switchotscraft.block.L70Block;
import net.mcreator.switchotscraft.block.L6Block;
import net.mcreator.switchotscraft.block.L69Block;
import net.mcreator.switchotscraft.block.L68Block;
import net.mcreator.switchotscraft.block.L67Block;
import net.mcreator.switchotscraft.block.L66Block;
import net.mcreator.switchotscraft.block.L65Block;
import net.mcreator.switchotscraft.block.L64Block;
import net.mcreator.switchotscraft.block.L63Block;
import net.mcreator.switchotscraft.block.L62Block;
import net.mcreator.switchotscraft.block.L61Block;
import net.mcreator.switchotscraft.block.L60Block;
import net.mcreator.switchotscraft.block.L5Block;
import net.mcreator.switchotscraft.block.L59Block;
import net.mcreator.switchotscraft.block.L58Block;
import net.mcreator.switchotscraft.block.L57Block;
import net.mcreator.switchotscraft.block.L56Block;
import net.mcreator.switchotscraft.block.L55Block;
import net.mcreator.switchotscraft.block.L54Block;
import net.mcreator.switchotscraft.block.L53Block;
import net.mcreator.switchotscraft.block.L52Block;
import net.mcreator.switchotscraft.block.L51Block;
import net.mcreator.switchotscraft.block.L50Block;
import net.mcreator.switchotscraft.block.L4Block;
import net.mcreator.switchotscraft.block.L49Block;
import net.mcreator.switchotscraft.block.L48Block;
import net.mcreator.switchotscraft.block.L47Block;
import net.mcreator.switchotscraft.block.L46Block;
import net.mcreator.switchotscraft.block.L45Block;
import net.mcreator.switchotscraft.block.L44Block;
import net.mcreator.switchotscraft.block.L43Block;
import net.mcreator.switchotscraft.block.L42Block;
import net.mcreator.switchotscraft.block.L41Block;
import net.mcreator.switchotscraft.block.L40Block;
import net.mcreator.switchotscraft.block.L3Block;
import net.mcreator.switchotscraft.block.L39Block;
import net.mcreator.switchotscraft.block.L38Block;
import net.mcreator.switchotscraft.block.L37Block;
import net.mcreator.switchotscraft.block.L36Block;
import net.mcreator.switchotscraft.block.L35Block;
import net.mcreator.switchotscraft.block.L34Block;
import net.mcreator.switchotscraft.block.L33Block;
import net.mcreator.switchotscraft.block.L32Block;
import net.mcreator.switchotscraft.block.L31Block;
import net.mcreator.switchotscraft.block.L30Block;
import net.mcreator.switchotscraft.block.L2Block;
import net.mcreator.switchotscraft.block.L29Block;
import net.mcreator.switchotscraft.block.L28Block;
import net.mcreator.switchotscraft.block.L27Block;
import net.mcreator.switchotscraft.block.L26Block;
import net.mcreator.switchotscraft.block.L25Block;
import net.mcreator.switchotscraft.block.L24Block;
import net.mcreator.switchotscraft.block.L23Block;
import net.mcreator.switchotscraft.block.L22Block;
import net.mcreator.switchotscraft.block.L21Block;
import net.mcreator.switchotscraft.block.L20Block;
import net.mcreator.switchotscraft.block.L200Block;
import net.mcreator.switchotscraft.block.L1Block;
import net.mcreator.switchotscraft.block.L19Block;
import net.mcreator.switchotscraft.block.L199Block;
import net.mcreator.switchotscraft.block.L198Block;
import net.mcreator.switchotscraft.block.L197Block;
import net.mcreator.switchotscraft.block.L196Block;
import net.mcreator.switchotscraft.block.L195Block;
import net.mcreator.switchotscraft.block.L194Block;
import net.mcreator.switchotscraft.block.L193Block;
import net.mcreator.switchotscraft.block.L192Block;
import net.mcreator.switchotscraft.block.L191Block;
import net.mcreator.switchotscraft.block.L190Block;
import net.mcreator.switchotscraft.block.L18Block;
import net.mcreator.switchotscraft.block.L189Block;
import net.mcreator.switchotscraft.block.L188Block;
import net.mcreator.switchotscraft.block.L187Block;
import net.mcreator.switchotscraft.block.L186Block;
import net.mcreator.switchotscraft.block.L185Block;
import net.mcreator.switchotscraft.block.L184Block;
import net.mcreator.switchotscraft.block.L183Block;
import net.mcreator.switchotscraft.block.L182Block;
import net.mcreator.switchotscraft.block.L181Block;
import net.mcreator.switchotscraft.block.L180Block;
import net.mcreator.switchotscraft.block.L17Block;
import net.mcreator.switchotscraft.block.L179Block;
import net.mcreator.switchotscraft.block.L178Block;
import net.mcreator.switchotscraft.block.L177Block;
import net.mcreator.switchotscraft.block.L176Block;
import net.mcreator.switchotscraft.block.L175Block;
import net.mcreator.switchotscraft.block.L174Block;
import net.mcreator.switchotscraft.block.L173Block;
import net.mcreator.switchotscraft.block.L172Block;
import net.mcreator.switchotscraft.block.L171Block;
import net.mcreator.switchotscraft.block.L170Block;
import net.mcreator.switchotscraft.block.L16Block;
import net.mcreator.switchotscraft.block.L169Block;
import net.mcreator.switchotscraft.block.L168Block;
import net.mcreator.switchotscraft.block.L167Block;
import net.mcreator.switchotscraft.block.L166Block;
import net.mcreator.switchotscraft.block.L165Block;
import net.mcreator.switchotscraft.block.L164Block;
import net.mcreator.switchotscraft.block.L163Block;
import net.mcreator.switchotscraft.block.L162Block;
import net.mcreator.switchotscraft.block.L161Block;
import net.mcreator.switchotscraft.block.L160Block;
import net.mcreator.switchotscraft.block.L15Block;
import net.mcreator.switchotscraft.block.L159Block;
import net.mcreator.switchotscraft.block.L158Block;
import net.mcreator.switchotscraft.block.L157Block;
import net.mcreator.switchotscraft.block.L156Block;
import net.mcreator.switchotscraft.block.L155Block;
import net.mcreator.switchotscraft.block.L154Block;
import net.mcreator.switchotscraft.block.L153Block;
import net.mcreator.switchotscraft.block.L152Block;
import net.mcreator.switchotscraft.block.L151Block;
import net.mcreator.switchotscraft.block.L150Block;
import net.mcreator.switchotscraft.block.L14Block;
import net.mcreator.switchotscraft.block.L149Block;
import net.mcreator.switchotscraft.block.L148Block;
import net.mcreator.switchotscraft.block.L147Block;
import net.mcreator.switchotscraft.block.L146Block;
import net.mcreator.switchotscraft.block.L145Block;
import net.mcreator.switchotscraft.block.L144Block;
import net.mcreator.switchotscraft.block.L143Block;
import net.mcreator.switchotscraft.block.L142Block;
import net.mcreator.switchotscraft.block.L141Block;
import net.mcreator.switchotscraft.block.L140Block;
import net.mcreator.switchotscraft.block.L13Block;
import net.mcreator.switchotscraft.block.L139Block;
import net.mcreator.switchotscraft.block.L138Block;
import net.mcreator.switchotscraft.block.L137Block;
import net.mcreator.switchotscraft.block.L136Block;
import net.mcreator.switchotscraft.block.L135Block;
import net.mcreator.switchotscraft.block.L134Block;
import net.mcreator.switchotscraft.block.L133Block;
import net.mcreator.switchotscraft.block.L132Block;
import net.mcreator.switchotscraft.block.L131Block;
import net.mcreator.switchotscraft.block.L130Block;
import net.mcreator.switchotscraft.block.L12Block;
import net.mcreator.switchotscraft.block.L129Block;
import net.mcreator.switchotscraft.block.L128Block;
import net.mcreator.switchotscraft.block.L127Block;
import net.mcreator.switchotscraft.block.L126Block;
import net.mcreator.switchotscraft.block.L125Block;
import net.mcreator.switchotscraft.block.L124Block;
import net.mcreator.switchotscraft.block.L123Block;
import net.mcreator.switchotscraft.block.L122Block;
import net.mcreator.switchotscraft.block.L121Block;
import net.mcreator.switchotscraft.block.L120Block;
import net.mcreator.switchotscraft.block.L11Block;
import net.mcreator.switchotscraft.block.L119Block;
import net.mcreator.switchotscraft.block.L118Block;
import net.mcreator.switchotscraft.block.L117Block;
import net.mcreator.switchotscraft.block.L116Block;
import net.mcreator.switchotscraft.block.L115Block;
import net.mcreator.switchotscraft.block.L114Block;
import net.mcreator.switchotscraft.block.L113Block;
import net.mcreator.switchotscraft.block.L112Block;
import net.mcreator.switchotscraft.block.L111Block;
import net.mcreator.switchotscraft.block.L110Block;
import net.mcreator.switchotscraft.block.L10Block;
import net.mcreator.switchotscraft.block.L109Block;
import net.mcreator.switchotscraft.block.L108Block;
import net.mcreator.switchotscraft.block.L107Block;
import net.mcreator.switchotscraft.block.L106Block;
import net.mcreator.switchotscraft.block.L105Block;
import net.mcreator.switchotscraft.block.L104Block;
import net.mcreator.switchotscraft.block.L103Block;
import net.mcreator.switchotscraft.block.L102Block;
import net.mcreator.switchotscraft.block.L101Block;
import net.mcreator.switchotscraft.block.L100Block;
import net.mcreator.switchotscraft.block.CuttingLogBlock;
import net.mcreator.switchotscraft.block.Cl9Block;
import net.mcreator.switchotscraft.block.Cl8Block;
import net.mcreator.switchotscraft.block.Cl7Block;
import net.mcreator.switchotscraft.block.Cl6Block;
import net.mcreator.switchotscraft.block.Cl5Block;
import net.mcreator.switchotscraft.block.Cl4Block;
import net.mcreator.switchotscraft.block.Cl3Block;
import net.mcreator.switchotscraft.block.Cl10Block;
import net.mcreator.switchotscraft.block.CL2Block;
import net.mcreator.switchotscraft.SwitchotsCraftMod;

public class SwitchotsCraftModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, SwitchotsCraftMod.MODID);
	public static final RegistryObject<Block> CUTTING_LOG = REGISTRY.register("cutting_log", () -> new CuttingLogBlock());
	public static final RegistryObject<Block> L_1 = REGISTRY.register("l_1", () -> new L1Block());
	public static final RegistryObject<Block> L_2 = REGISTRY.register("l_2", () -> new L2Block());
	public static final RegistryObject<Block> L_3 = REGISTRY.register("l_3", () -> new L3Block());
	public static final RegistryObject<Block> L_4 = REGISTRY.register("l_4", () -> new L4Block());
	public static final RegistryObject<Block> L_5 = REGISTRY.register("l_5", () -> new L5Block());
	public static final RegistryObject<Block> L_6 = REGISTRY.register("l_6", () -> new L6Block());
	public static final RegistryObject<Block> L_7 = REGISTRY.register("l_7", () -> new L7Block());
	public static final RegistryObject<Block> L_8 = REGISTRY.register("l_8", () -> new L8Block());
	public static final RegistryObject<Block> L_9 = REGISTRY.register("l_9", () -> new L9Block());
	public static final RegistryObject<Block> L_10 = REGISTRY.register("l_10", () -> new L10Block());
	public static final RegistryObject<Block> L_11 = REGISTRY.register("l_11", () -> new L11Block());
	public static final RegistryObject<Block> L_12 = REGISTRY.register("l_12", () -> new L12Block());
	public static final RegistryObject<Block> L_13 = REGISTRY.register("l_13", () -> new L13Block());
	public static final RegistryObject<Block> L_14 = REGISTRY.register("l_14", () -> new L14Block());
	public static final RegistryObject<Block> L_15 = REGISTRY.register("l_15", () -> new L15Block());
	public static final RegistryObject<Block> L_16 = REGISTRY.register("l_16", () -> new L16Block());
	public static final RegistryObject<Block> L_17 = REGISTRY.register("l_17", () -> new L17Block());
	public static final RegistryObject<Block> L_18 = REGISTRY.register("l_18", () -> new L18Block());
	public static final RegistryObject<Block> L_19 = REGISTRY.register("l_19", () -> new L19Block());
	public static final RegistryObject<Block> L_20 = REGISTRY.register("l_20", () -> new L20Block());
	public static final RegistryObject<Block> L_21 = REGISTRY.register("l_21", () -> new L21Block());
	public static final RegistryObject<Block> L_22 = REGISTRY.register("l_22", () -> new L22Block());
	public static final RegistryObject<Block> L_23 = REGISTRY.register("l_23", () -> new L23Block());
	public static final RegistryObject<Block> L_24 = REGISTRY.register("l_24", () -> new L24Block());
	public static final RegistryObject<Block> L_25 = REGISTRY.register("l_25", () -> new L25Block());
	public static final RegistryObject<Block> L_26 = REGISTRY.register("l_26", () -> new L26Block());
	public static final RegistryObject<Block> L_27 = REGISTRY.register("l_27", () -> new L27Block());
	public static final RegistryObject<Block> L_28 = REGISTRY.register("l_28", () -> new L28Block());
	public static final RegistryObject<Block> L_29 = REGISTRY.register("l_29", () -> new L29Block());
	public static final RegistryObject<Block> L_30 = REGISTRY.register("l_30", () -> new L30Block());
	public static final RegistryObject<Block> L_31 = REGISTRY.register("l_31", () -> new L31Block());
	public static final RegistryObject<Block> L_32 = REGISTRY.register("l_32", () -> new L32Block());
	public static final RegistryObject<Block> L_33 = REGISTRY.register("l_33", () -> new L33Block());
	public static final RegistryObject<Block> L_34 = REGISTRY.register("l_34", () -> new L34Block());
	public static final RegistryObject<Block> L_35 = REGISTRY.register("l_35", () -> new L35Block());
	public static final RegistryObject<Block> L_36 = REGISTRY.register("l_36", () -> new L36Block());
	public static final RegistryObject<Block> L_37 = REGISTRY.register("l_37", () -> new L37Block());
	public static final RegistryObject<Block> L_38 = REGISTRY.register("l_38", () -> new L38Block());
	public static final RegistryObject<Block> L_39 = REGISTRY.register("l_39", () -> new L39Block());
	public static final RegistryObject<Block> L_40 = REGISTRY.register("l_40", () -> new L40Block());
	public static final RegistryObject<Block> L_41 = REGISTRY.register("l_41", () -> new L41Block());
	public static final RegistryObject<Block> L_42 = REGISTRY.register("l_42", () -> new L42Block());
	public static final RegistryObject<Block> L_43 = REGISTRY.register("l_43", () -> new L43Block());
	public static final RegistryObject<Block> L_44 = REGISTRY.register("l_44", () -> new L44Block());
	public static final RegistryObject<Block> L_45 = REGISTRY.register("l_45", () -> new L45Block());
	public static final RegistryObject<Block> L_46 = REGISTRY.register("l_46", () -> new L46Block());
	public static final RegistryObject<Block> L_47 = REGISTRY.register("l_47", () -> new L47Block());
	public static final RegistryObject<Block> L_48 = REGISTRY.register("l_48", () -> new L48Block());
	public static final RegistryObject<Block> L_49 = REGISTRY.register("l_49", () -> new L49Block());
	public static final RegistryObject<Block> L_50 = REGISTRY.register("l_50", () -> new L50Block());
	public static final RegistryObject<Block> L_51 = REGISTRY.register("l_51", () -> new L51Block());
	public static final RegistryObject<Block> L_52 = REGISTRY.register("l_52", () -> new L52Block());
	public static final RegistryObject<Block> L_53 = REGISTRY.register("l_53", () -> new L53Block());
	public static final RegistryObject<Block> L_54 = REGISTRY.register("l_54", () -> new L54Block());
	public static final RegistryObject<Block> L_55 = REGISTRY.register("l_55", () -> new L55Block());
	public static final RegistryObject<Block> L_56 = REGISTRY.register("l_56", () -> new L56Block());
	public static final RegistryObject<Block> L_57 = REGISTRY.register("l_57", () -> new L57Block());
	public static final RegistryObject<Block> L_58 = REGISTRY.register("l_58", () -> new L58Block());
	public static final RegistryObject<Block> L_59 = REGISTRY.register("l_59", () -> new L59Block());
	public static final RegistryObject<Block> L_60 = REGISTRY.register("l_60", () -> new L60Block());
	public static final RegistryObject<Block> L_61 = REGISTRY.register("l_61", () -> new L61Block());
	public static final RegistryObject<Block> L_62 = REGISTRY.register("l_62", () -> new L62Block());
	public static final RegistryObject<Block> L_63 = REGISTRY.register("l_63", () -> new L63Block());
	public static final RegistryObject<Block> L_64 = REGISTRY.register("l_64", () -> new L64Block());
	public static final RegistryObject<Block> L_65 = REGISTRY.register("l_65", () -> new L65Block());
	public static final RegistryObject<Block> L_66 = REGISTRY.register("l_66", () -> new L66Block());
	public static final RegistryObject<Block> L_67 = REGISTRY.register("l_67", () -> new L67Block());
	public static final RegistryObject<Block> L_68 = REGISTRY.register("l_68", () -> new L68Block());
	public static final RegistryObject<Block> L_69 = REGISTRY.register("l_69", () -> new L69Block());
	public static final RegistryObject<Block> L_70 = REGISTRY.register("l_70", () -> new L70Block());
	public static final RegistryObject<Block> L_71 = REGISTRY.register("l_71", () -> new L71Block());
	public static final RegistryObject<Block> L_72 = REGISTRY.register("l_72", () -> new L72Block());
	public static final RegistryObject<Block> L_73 = REGISTRY.register("l_73", () -> new L73Block());
	public static final RegistryObject<Block> L_74 = REGISTRY.register("l_74", () -> new L74Block());
	public static final RegistryObject<Block> L_75 = REGISTRY.register("l_75", () -> new L75Block());
	public static final RegistryObject<Block> L_76 = REGISTRY.register("l_76", () -> new L76Block());
	public static final RegistryObject<Block> L_77 = REGISTRY.register("l_77", () -> new L77Block());
	public static final RegistryObject<Block> L_78 = REGISTRY.register("l_78", () -> new L78Block());
	public static final RegistryObject<Block> L_79 = REGISTRY.register("l_79", () -> new L79Block());
	public static final RegistryObject<Block> L_80 = REGISTRY.register("l_80", () -> new L80Block());
	public static final RegistryObject<Block> L_81 = REGISTRY.register("l_81", () -> new L81Block());
	public static final RegistryObject<Block> L_82 = REGISTRY.register("l_82", () -> new L82Block());
	public static final RegistryObject<Block> L_83 = REGISTRY.register("l_83", () -> new L83Block());
	public static final RegistryObject<Block> L_84 = REGISTRY.register("l_84", () -> new L84Block());
	public static final RegistryObject<Block> L_85 = REGISTRY.register("l_85", () -> new L85Block());
	public static final RegistryObject<Block> L_86 = REGISTRY.register("l_86", () -> new L86Block());
	public static final RegistryObject<Block> L_87 = REGISTRY.register("l_87", () -> new L87Block());
	public static final RegistryObject<Block> L_88 = REGISTRY.register("l_88", () -> new L88Block());
	public static final RegistryObject<Block> L_89 = REGISTRY.register("l_89", () -> new L89Block());
	public static final RegistryObject<Block> L_90 = REGISTRY.register("l_90", () -> new L90Block());
	public static final RegistryObject<Block> L_91 = REGISTRY.register("l_91", () -> new L91Block());
	public static final RegistryObject<Block> L_92 = REGISTRY.register("l_92", () -> new L92Block());
	public static final RegistryObject<Block> L_93 = REGISTRY.register("l_93", () -> new L93Block());
	public static final RegistryObject<Block> L_94 = REGISTRY.register("l_94", () -> new L94Block());
	public static final RegistryObject<Block> L_95 = REGISTRY.register("l_95", () -> new L95Block());
	public static final RegistryObject<Block> L_96 = REGISTRY.register("l_96", () -> new L96Block());
	public static final RegistryObject<Block> L_97 = REGISTRY.register("l_97", () -> new L97Block());
	public static final RegistryObject<Block> L_98 = REGISTRY.register("l_98", () -> new L98Block());
	public static final RegistryObject<Block> L_99 = REGISTRY.register("l_99", () -> new L99Block());
	public static final RegistryObject<Block> L_100 = REGISTRY.register("l_100", () -> new L100Block());
	public static final RegistryObject<Block> L_101 = REGISTRY.register("l_101", () -> new L101Block());
	public static final RegistryObject<Block> L_102 = REGISTRY.register("l_102", () -> new L102Block());
	public static final RegistryObject<Block> L_103 = REGISTRY.register("l_103", () -> new L103Block());
	public static final RegistryObject<Block> L_104 = REGISTRY.register("l_104", () -> new L104Block());
	public static final RegistryObject<Block> L_105 = REGISTRY.register("l_105", () -> new L105Block());
	public static final RegistryObject<Block> L_106 = REGISTRY.register("l_106", () -> new L106Block());
	public static final RegistryObject<Block> L_107 = REGISTRY.register("l_107", () -> new L107Block());
	public static final RegistryObject<Block> L_108 = REGISTRY.register("l_108", () -> new L108Block());
	public static final RegistryObject<Block> L_109 = REGISTRY.register("l_109", () -> new L109Block());
	public static final RegistryObject<Block> L_110 = REGISTRY.register("l_110", () -> new L110Block());
	public static final RegistryObject<Block> L_111 = REGISTRY.register("l_111", () -> new L111Block());
	public static final RegistryObject<Block> L_112 = REGISTRY.register("l_112", () -> new L112Block());
	public static final RegistryObject<Block> L_113 = REGISTRY.register("l_113", () -> new L113Block());
	public static final RegistryObject<Block> L_114 = REGISTRY.register("l_114", () -> new L114Block());
	public static final RegistryObject<Block> L_115 = REGISTRY.register("l_115", () -> new L115Block());
	public static final RegistryObject<Block> L_116 = REGISTRY.register("l_116", () -> new L116Block());
	public static final RegistryObject<Block> L_117 = REGISTRY.register("l_117", () -> new L117Block());
	public static final RegistryObject<Block> L_118 = REGISTRY.register("l_118", () -> new L118Block());
	public static final RegistryObject<Block> L_119 = REGISTRY.register("l_119", () -> new L119Block());
	public static final RegistryObject<Block> L_120 = REGISTRY.register("l_120", () -> new L120Block());
	public static final RegistryObject<Block> L_121 = REGISTRY.register("l_121", () -> new L121Block());
	public static final RegistryObject<Block> L_122 = REGISTRY.register("l_122", () -> new L122Block());
	public static final RegistryObject<Block> L_123 = REGISTRY.register("l_123", () -> new L123Block());
	public static final RegistryObject<Block> L_124 = REGISTRY.register("l_124", () -> new L124Block());
	public static final RegistryObject<Block> L_125 = REGISTRY.register("l_125", () -> new L125Block());
	public static final RegistryObject<Block> L_126 = REGISTRY.register("l_126", () -> new L126Block());
	public static final RegistryObject<Block> L_127 = REGISTRY.register("l_127", () -> new L127Block());
	public static final RegistryObject<Block> L_128 = REGISTRY.register("l_128", () -> new L128Block());
	public static final RegistryObject<Block> L_129 = REGISTRY.register("l_129", () -> new L129Block());
	public static final RegistryObject<Block> L_130 = REGISTRY.register("l_130", () -> new L130Block());
	public static final RegistryObject<Block> L_131 = REGISTRY.register("l_131", () -> new L131Block());
	public static final RegistryObject<Block> L_132 = REGISTRY.register("l_132", () -> new L132Block());
	public static final RegistryObject<Block> L_133 = REGISTRY.register("l_133", () -> new L133Block());
	public static final RegistryObject<Block> L_134 = REGISTRY.register("l_134", () -> new L134Block());
	public static final RegistryObject<Block> L_135 = REGISTRY.register("l_135", () -> new L135Block());
	public static final RegistryObject<Block> L_136 = REGISTRY.register("l_136", () -> new L136Block());
	public static final RegistryObject<Block> L_137 = REGISTRY.register("l_137", () -> new L137Block());
	public static final RegistryObject<Block> L_138 = REGISTRY.register("l_138", () -> new L138Block());
	public static final RegistryObject<Block> L_139 = REGISTRY.register("l_139", () -> new L139Block());
	public static final RegistryObject<Block> L_140 = REGISTRY.register("l_140", () -> new L140Block());
	public static final RegistryObject<Block> L_141 = REGISTRY.register("l_141", () -> new L141Block());
	public static final RegistryObject<Block> L_142 = REGISTRY.register("l_142", () -> new L142Block());
	public static final RegistryObject<Block> L_143 = REGISTRY.register("l_143", () -> new L143Block());
	public static final RegistryObject<Block> L_144 = REGISTRY.register("l_144", () -> new L144Block());
	public static final RegistryObject<Block> L_145 = REGISTRY.register("l_145", () -> new L145Block());
	public static final RegistryObject<Block> L_146 = REGISTRY.register("l_146", () -> new L146Block());
	public static final RegistryObject<Block> L_147 = REGISTRY.register("l_147", () -> new L147Block());
	public static final RegistryObject<Block> L_148 = REGISTRY.register("l_148", () -> new L148Block());
	public static final RegistryObject<Block> L_149 = REGISTRY.register("l_149", () -> new L149Block());
	public static final RegistryObject<Block> L_150 = REGISTRY.register("l_150", () -> new L150Block());
	public static final RegistryObject<Block> L_151 = REGISTRY.register("l_151", () -> new L151Block());
	public static final RegistryObject<Block> L_152 = REGISTRY.register("l_152", () -> new L152Block());
	public static final RegistryObject<Block> L_153 = REGISTRY.register("l_153", () -> new L153Block());
	public static final RegistryObject<Block> L_154 = REGISTRY.register("l_154", () -> new L154Block());
	public static final RegistryObject<Block> L_155 = REGISTRY.register("l_155", () -> new L155Block());
	public static final RegistryObject<Block> L_156 = REGISTRY.register("l_156", () -> new L156Block());
	public static final RegistryObject<Block> L_157 = REGISTRY.register("l_157", () -> new L157Block());
	public static final RegistryObject<Block> L_158 = REGISTRY.register("l_158", () -> new L158Block());
	public static final RegistryObject<Block> L_159 = REGISTRY.register("l_159", () -> new L159Block());
	public static final RegistryObject<Block> L_160 = REGISTRY.register("l_160", () -> new L160Block());
	public static final RegistryObject<Block> L_161 = REGISTRY.register("l_161", () -> new L161Block());
	public static final RegistryObject<Block> L_162 = REGISTRY.register("l_162", () -> new L162Block());
	public static final RegistryObject<Block> L_163 = REGISTRY.register("l_163", () -> new L163Block());
	public static final RegistryObject<Block> L_164 = REGISTRY.register("l_164", () -> new L164Block());
	public static final RegistryObject<Block> L_165 = REGISTRY.register("l_165", () -> new L165Block());
	public static final RegistryObject<Block> L_166 = REGISTRY.register("l_166", () -> new L166Block());
	public static final RegistryObject<Block> L_167 = REGISTRY.register("l_167", () -> new L167Block());
	public static final RegistryObject<Block> L_168 = REGISTRY.register("l_168", () -> new L168Block());
	public static final RegistryObject<Block> L_169 = REGISTRY.register("l_169", () -> new L169Block());
	public static final RegistryObject<Block> L_170 = REGISTRY.register("l_170", () -> new L170Block());
	public static final RegistryObject<Block> L_171 = REGISTRY.register("l_171", () -> new L171Block());
	public static final RegistryObject<Block> L_172 = REGISTRY.register("l_172", () -> new L172Block());
	public static final RegistryObject<Block> L_173 = REGISTRY.register("l_173", () -> new L173Block());
	public static final RegistryObject<Block> L_174 = REGISTRY.register("l_174", () -> new L174Block());
	public static final RegistryObject<Block> L_175 = REGISTRY.register("l_175", () -> new L175Block());
	public static final RegistryObject<Block> L_176 = REGISTRY.register("l_176", () -> new L176Block());
	public static final RegistryObject<Block> L_177 = REGISTRY.register("l_177", () -> new L177Block());
	public static final RegistryObject<Block> L_178 = REGISTRY.register("l_178", () -> new L178Block());
	public static final RegistryObject<Block> L_179 = REGISTRY.register("l_179", () -> new L179Block());
	public static final RegistryObject<Block> L_180 = REGISTRY.register("l_180", () -> new L180Block());
	public static final RegistryObject<Block> L_181 = REGISTRY.register("l_181", () -> new L181Block());
	public static final RegistryObject<Block> L_182 = REGISTRY.register("l_182", () -> new L182Block());
	public static final RegistryObject<Block> L_183 = REGISTRY.register("l_183", () -> new L183Block());
	public static final RegistryObject<Block> L_184 = REGISTRY.register("l_184", () -> new L184Block());
	public static final RegistryObject<Block> L_185 = REGISTRY.register("l_185", () -> new L185Block());
	public static final RegistryObject<Block> L_186 = REGISTRY.register("l_186", () -> new L186Block());
	public static final RegistryObject<Block> L_187 = REGISTRY.register("l_187", () -> new L187Block());
	public static final RegistryObject<Block> L_188 = REGISTRY.register("l_188", () -> new L188Block());
	public static final RegistryObject<Block> L_189 = REGISTRY.register("l_189", () -> new L189Block());
	public static final RegistryObject<Block> L_190 = REGISTRY.register("l_190", () -> new L190Block());
	public static final RegistryObject<Block> L_191 = REGISTRY.register("l_191", () -> new L191Block());
	public static final RegistryObject<Block> L_192 = REGISTRY.register("l_192", () -> new L192Block());
	public static final RegistryObject<Block> L_193 = REGISTRY.register("l_193", () -> new L193Block());
	public static final RegistryObject<Block> L_194 = REGISTRY.register("l_194", () -> new L194Block());
	public static final RegistryObject<Block> L_195 = REGISTRY.register("l_195", () -> new L195Block());
	public static final RegistryObject<Block> L_196 = REGISTRY.register("l_196", () -> new L196Block());
	public static final RegistryObject<Block> L_197 = REGISTRY.register("l_197", () -> new L197Block());
	public static final RegistryObject<Block> L_198 = REGISTRY.register("l_198", () -> new L198Block());
	public static final RegistryObject<Block> L_199 = REGISTRY.register("l_199", () -> new L199Block());
	public static final RegistryObject<Block> L_200 = REGISTRY.register("l_200", () -> new L200Block());
	public static final RegistryObject<Block> P_1 = REGISTRY.register("p_1", () -> new P1Block());
	public static final RegistryObject<Block> P_2 = REGISTRY.register("p_2", () -> new P2Block());
	public static final RegistryObject<Block> P_3 = REGISTRY.register("p_3", () -> new P3Block());
	public static final RegistryObject<Block> P_4 = REGISTRY.register("p_4", () -> new P4Block());
	public static final RegistryObject<Block> P_5 = REGISTRY.register("p_5", () -> new P5Block());
	public static final RegistryObject<Block> P_6 = REGISTRY.register("p_6", () -> new P6Block());
	public static final RegistryObject<Block> P_7 = REGISTRY.register("p_7", () -> new P7Block());
	public static final RegistryObject<Block> P_8 = REGISTRY.register("p_8", () -> new P8Block());
	public static final RegistryObject<Block> P_9 = REGISTRY.register("p_9", () -> new P9Block());
	public static final RegistryObject<Block> P_10 = REGISTRY.register("p_10", () -> new P10Block());
	public static final RegistryObject<Block> P_11 = REGISTRY.register("p_11", () -> new P11Block());
	public static final RegistryObject<Block> P_12 = REGISTRY.register("p_12", () -> new P12Block());
	public static final RegistryObject<Block> P_13 = REGISTRY.register("p_13", () -> new P13Block());
	public static final RegistryObject<Block> P_14 = REGISTRY.register("p_14", () -> new P14Block());
	public static final RegistryObject<Block> P_15 = REGISTRY.register("p_15", () -> new P15Block());
	public static final RegistryObject<Block> P_16 = REGISTRY.register("p_16", () -> new P16Block());
	public static final RegistryObject<Block> P_17 = REGISTRY.register("p_17", () -> new P17Block());
	public static final RegistryObject<Block> P_18 = REGISTRY.register("p_18", () -> new P18Block());
	public static final RegistryObject<Block> P_19 = REGISTRY.register("p_19", () -> new P19Block());
	public static final RegistryObject<Block> P_20 = REGISTRY.register("p_20", () -> new P20Block());
	public static final RegistryObject<Block> P_21 = REGISTRY.register("p_21", () -> new P21Block());
	public static final RegistryObject<Block> P_22 = REGISTRY.register("p_22", () -> new P22Block());
	public static final RegistryObject<Block> P_23 = REGISTRY.register("p_23", () -> new P23Block());
	public static final RegistryObject<Block> P_24 = REGISTRY.register("p_24", () -> new P24Block());
	public static final RegistryObject<Block> P_25 = REGISTRY.register("p_25", () -> new P25Block());
	public static final RegistryObject<Block> P_26 = REGISTRY.register("p_26", () -> new P26Block());
	public static final RegistryObject<Block> P_27 = REGISTRY.register("p_27", () -> new P27Block());
	public static final RegistryObject<Block> P_28 = REGISTRY.register("p_28", () -> new P28Block());
	public static final RegistryObject<Block> P_29 = REGISTRY.register("p_29", () -> new P29Block());
	public static final RegistryObject<Block> P_30 = REGISTRY.register("p_30", () -> new P30Block());
	public static final RegistryObject<Block> P_31 = REGISTRY.register("p_31", () -> new P31Block());
	public static final RegistryObject<Block> P_32 = REGISTRY.register("p_32", () -> new P32Block());
	public static final RegistryObject<Block> P_33 = REGISTRY.register("p_33", () -> new P33Block());
	public static final RegistryObject<Block> P_34 = REGISTRY.register("p_34", () -> new P34Block());
	public static final RegistryObject<Block> P_35 = REGISTRY.register("p_35", () -> new P35Block());
	public static final RegistryObject<Block> P_36 = REGISTRY.register("p_36", () -> new P36Block());
	public static final RegistryObject<Block> P_37 = REGISTRY.register("p_37", () -> new P37Block());
	public static final RegistryObject<Block> P_38 = REGISTRY.register("p_38", () -> new P38Block());
	public static final RegistryObject<Block> P_39 = REGISTRY.register("p_39", () -> new P39Block());
	public static final RegistryObject<Block> P_40 = REGISTRY.register("p_40", () -> new P40Block());
	public static final RegistryObject<Block> P_41 = REGISTRY.register("p_41", () -> new P41Block());
	public static final RegistryObject<Block> P_42 = REGISTRY.register("p_42", () -> new P42Block());
	public static final RegistryObject<Block> P_43 = REGISTRY.register("p_43", () -> new P43Block());
	public static final RegistryObject<Block> P_44 = REGISTRY.register("p_44", () -> new P44Block());
	public static final RegistryObject<Block> P_45 = REGISTRY.register("p_45", () -> new P45Block());
	public static final RegistryObject<Block> P_46 = REGISTRY.register("p_46", () -> new P46Block());
	public static final RegistryObject<Block> P_47 = REGISTRY.register("p_47", () -> new P47Block());
	public static final RegistryObject<Block> P_48 = REGISTRY.register("p_48", () -> new P48Block());
	public static final RegistryObject<Block> P_49 = REGISTRY.register("p_49", () -> new P49Block());
	public static final RegistryObject<Block> P_50 = REGISTRY.register("p_50", () -> new P50Block());
	public static final RegistryObject<Block> P_51 = REGISTRY.register("p_51", () -> new P51Block());
	public static final RegistryObject<Block> P_52 = REGISTRY.register("p_52", () -> new P52Block());
	public static final RegistryObject<Block> P_53 = REGISTRY.register("p_53", () -> new P53Block());
	public static final RegistryObject<Block> P_54 = REGISTRY.register("p_54", () -> new P54Block());
	public static final RegistryObject<Block> P_55 = REGISTRY.register("p_55", () -> new P55Block());
	public static final RegistryObject<Block> P_56 = REGISTRY.register("p_56", () -> new P56Block());
	public static final RegistryObject<Block> P_57 = REGISTRY.register("p_57", () -> new P57Block());
	public static final RegistryObject<Block> P_58 = REGISTRY.register("p_58", () -> new P58Block());
	public static final RegistryObject<Block> P_59 = REGISTRY.register("p_59", () -> new P59Block());
	public static final RegistryObject<Block> P_60 = REGISTRY.register("p_60", () -> new P60Block());
	public static final RegistryObject<Block> P_61 = REGISTRY.register("p_61", () -> new P61Block());
	public static final RegistryObject<Block> P_62 = REGISTRY.register("p_62", () -> new P62Block());
	public static final RegistryObject<Block> P_63 = REGISTRY.register("p_63", () -> new P63Block());
	public static final RegistryObject<Block> P_64 = REGISTRY.register("p_64", () -> new P64Block());
	public static final RegistryObject<Block> P_65 = REGISTRY.register("p_65", () -> new P65Block());
	public static final RegistryObject<Block> P_66 = REGISTRY.register("p_66", () -> new P66Block());
	public static final RegistryObject<Block> P_67 = REGISTRY.register("p_67", () -> new P67Block());
	public static final RegistryObject<Block> P_68 = REGISTRY.register("p_68", () -> new P68Block());
	public static final RegistryObject<Block> P_69 = REGISTRY.register("p_69", () -> new P69Block());
	public static final RegistryObject<Block> P_70 = REGISTRY.register("p_70", () -> new P70Block());
	public static final RegistryObject<Block> P_71 = REGISTRY.register("p_71", () -> new P71Block());
	public static final RegistryObject<Block> P_72 = REGISTRY.register("p_72", () -> new P72Block());
	public static final RegistryObject<Block> P_73 = REGISTRY.register("p_73", () -> new P73Block());
	public static final RegistryObject<Block> P_74 = REGISTRY.register("p_74", () -> new P74Block());
	public static final RegistryObject<Block> P_75 = REGISTRY.register("p_75", () -> new P75Block());
	public static final RegistryObject<Block> P_76 = REGISTRY.register("p_76", () -> new P76Block());
	public static final RegistryObject<Block> P_77 = REGISTRY.register("p_77", () -> new P77Block());
	public static final RegistryObject<Block> P_78 = REGISTRY.register("p_78", () -> new P78Block());
	public static final RegistryObject<Block> P_79 = REGISTRY.register("p_79", () -> new P79Block());
	public static final RegistryObject<Block> P_80 = REGISTRY.register("p_80", () -> new P80Block());
	public static final RegistryObject<Block> P_81 = REGISTRY.register("p_81", () -> new P81Block());
	public static final RegistryObject<Block> P_82 = REGISTRY.register("p_82", () -> new P82Block());
	public static final RegistryObject<Block> P_83 = REGISTRY.register("p_83", () -> new P83Block());
	public static final RegistryObject<Block> P_84 = REGISTRY.register("p_84", () -> new P84Block());
	public static final RegistryObject<Block> P_85 = REGISTRY.register("p_85", () -> new P85Block());
	public static final RegistryObject<Block> P_86 = REGISTRY.register("p_86", () -> new P86Block());
	public static final RegistryObject<Block> P_87 = REGISTRY.register("p_87", () -> new P87Block());
	public static final RegistryObject<Block> P_88 = REGISTRY.register("p_88", () -> new P88Block());
	public static final RegistryObject<Block> P_89 = REGISTRY.register("p_89", () -> new P89Block());
	public static final RegistryObject<Block> P_90 = REGISTRY.register("p_90", () -> new P90Block());
	public static final RegistryObject<Block> P_91 = REGISTRY.register("p_91", () -> new P91Block());
	public static final RegistryObject<Block> P_92 = REGISTRY.register("p_92", () -> new P92Block());
	public static final RegistryObject<Block> P_93 = REGISTRY.register("p_93", () -> new P93Block());
	public static final RegistryObject<Block> P_94 = REGISTRY.register("p_94", () -> new P94Block());
	public static final RegistryObject<Block> P_95 = REGISTRY.register("p_95", () -> new P95Block());
	public static final RegistryObject<Block> P_96 = REGISTRY.register("p_96", () -> new P96Block());
	public static final RegistryObject<Block> P_97 = REGISTRY.register("p_97", () -> new P97Block());
	public static final RegistryObject<Block> P_98 = REGISTRY.register("p_98", () -> new P98Block());
	public static final RegistryObject<Block> P_99 = REGISTRY.register("p_99", () -> new P99Block());
	public static final RegistryObject<Block> P_100 = REGISTRY.register("p_100", () -> new P100Block());
	public static final RegistryObject<Block> CL_2 = REGISTRY.register("cl_2", () -> new CL2Block());
	public static final RegistryObject<Block> CL_3 = REGISTRY.register("cl_3", () -> new Cl3Block());
	public static final RegistryObject<Block> CL_4 = REGISTRY.register("cl_4", () -> new Cl4Block());
	public static final RegistryObject<Block> CL_5 = REGISTRY.register("cl_5", () -> new Cl5Block());
	public static final RegistryObject<Block> CL_6 = REGISTRY.register("cl_6", () -> new Cl6Block());
	public static final RegistryObject<Block> CL_7 = REGISTRY.register("cl_7", () -> new Cl7Block());
	public static final RegistryObject<Block> CL_8 = REGISTRY.register("cl_8", () -> new Cl8Block());
	public static final RegistryObject<Block> CL_9 = REGISTRY.register("cl_9", () -> new Cl9Block());
	public static final RegistryObject<Block> CL_10 = REGISTRY.register("cl_10", () -> new Cl10Block());
}
